[package]
name = "tracing-poc"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
opentelemetry = "0.22.0"
opentelemetry_sdk = "0.22.1"
opentelemetry-stdout = { version = "0.3.0", features = ["trace"] }
